### ISSUE TITLE
[DOCS]: Examples should mirror plugins folder structure

### ISSUE THREAD

**Issue by debkanchan** [TheFireCo/genkit-plugins#128]
IMO first there should be examples of each plugin and second, each example of a plugin should be a seperate npm project so they are independently runnable and maintainable.

I ideal dir structure for example like this
```
- plugins
  ⌙ anthropic
    ⌙ pacakge.json
...

- examples
  ⌙ anthropic
    ⌙ package.json
```

I just tried to make a new npm project under example and it always modified the current parent package.json in`/examples`

**Comment by xavidop** [comment]
this is done!
