### ISSUE TITLE
Release newest anthropic models in next version

### ISSUE THREAD

**Issue by matzeso** [TheFireCo/genkit-plugins#197]
**Is your feature request related to a problem? Please describe.**
The newest version of 3.5 sonnet and 3.5 haiku are not supported in the latest release.

**Describe the solution you'd like**
As it has already been implemented and merged, it would be great if someone could do a release und push it to the NPM registry :) 

**Describe alternatives you've considered**
I considered building on my own, but would prefer not to. Currently I'm manually overwriting the ReferenceModel strings.

**Additional context**
-

Thanks for the great plugin and have a happy new year 🔥

**Comment by xavidop** [comment]
it is out now: https://github.com/TheFireCo/genkit-plugins/discussions/203

**Comment by rednikisfun** [comment]
I'm trying to use Haiku 3.5 with the latest version of anthropic plugin (v 0.12.0).

However, when I try to import `claude35haiku` I can't find it.

I looked into the index.d.ts, and claude.t..ts, and I can see there's a claude35haiku, but it's not exported.

It's very confusing that in the changelogs of v0.12.0 there's support of haiku 3.5 mentioned, but in reality, we still can't access it from the plugin. 

If we can, would be great to have a documentation on how to do that.

**Comment by xavidop** [comment]
@rednikisfun https://github.com/TheFireCo/genkit-plugins/pull/208

**Comment by xavidop** [comment]
@rednikisfun it is out now in v0.13.0
