### ISSUE TITLE
Feature Request: support format: "json" in gpt models

### ISSUE THREAD

**Issue by cabljac** [TheFireCo/genkit-plugins#53]
Hi, I was using the OpenAI plugin a week ago and it didn't seem to support `format: "json"` in the gpt4 model (and others maybe)

Would be great to have this, some of my flows I want to switch between Gemini and GPT, and this would make it more seemless

**Comment by Dabolus** [comment]
Thanks for opening the issue. Which model are you using specifically? Because both GPT-4o and GPT-4 Turbo should already support JSON, while GPT-4 and GPT-4 Vision do not support it

**Comment by Dabolus** [comment]
@cabljac I would suggest to use the GPT-4o model as it works better, costs less, and supports JSON mode. I'll close the issue, but feel free to re-open it if you encounter the problem also with GPT-4o
