### ISSUE TITLE
Finalize OpenAI Azure Plugin

### ISSUE THREAD

**Issue by davidoort** [TheFireCo/genkit-plugins#69]
We're looking for a code owner for the OpenAI Azure Plugin that can take the current skeleton (which doesn't work) and turn it into a working plugin.

**Comment by archasek** [comment]
Yeah, I need that :-D. Also with embedding models and api version support.

**Comment by xavidop** [comment]
> Will this ever be fixed.

it will

**Comment by xavidop** [comment]
PR: https://github.com/TheFireCo/genkit-plugins/pull/194

**Comment by xavidop** [comment]
plugin is now available!
